name: bugtracker
channels:
  - conda-forge
  - defaults
dependencies:
  - arm_pyart
  - asn1crypto
  - beautifulsoup4
  - blas
  - bzip2
  - ca-certificates
  - cartopy
  - certifi
  - cffi
  - cftime
  - chardet
  - cryptography
  - curl
  - cycler
  - freetype
  - geographiclib
  - geopy
  - geos
  - hdf4
  - hdf5
  - icc_rt
  - icu
  - idna
  - intel-openmp
  - jpeg
  - kiwisolver
  - krb5
  - libcurl
  - libiconv
  - libnetcdf
  - libpng
  - libssh2
  - libtiff
  - libxml2
  - libxslt
  - lxml
  - matplotlib
  - matplotlib-base
  - mkl
  - mkl-service
  - mkl_fft
  - mkl_random
  - netcdf4
  - numpy
  - numpy-base
  - olefile
  - openssl
  - owslib
  - pandas
  - pillow
  - pip
  - proj4
  - psutil
  - pycparser
  - pyepsg
  - pykdtree
  - pyopenssl
  - pyparsing
  - pyproj
  - pyqt
  - pyshp
  - pysocks
  - python=3.7
  - python-dateutil
  - pytz
  - qt
  - requests
  - scipy
  - setuptools
  - shapely
  - sip
  - six
  - soupsieve
  - sqlite
  - tk
  - tornado
  - urllib3
  - vc
  - vs2015_runtime
  - wheel
  - win_inet_pton
  - wincertstore
  - xarray
  - xz
  - zlib
  - zstd
  - pip:
    - atomicwrites
    - attrs
    - bugtracker
    - colorama
    - importlib-metadata
    - more-itertools
    - opencv-python
    - packaging
    - pluggy
    - py
    - pytest
    - wcwidth
    - zipp

