name: bugtracker
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - arm_pyart
  - beautifulsoup4
  - bzip2
  - ca-certificates
  - cartopy
  - certifi
  - cffi
  - cftime
  - chardet
  - cryptography
  - curl
  - cycler
  - dbus
  - expat
  - fontconfig
  - freetype
  - geographiclib
  - geopy
  - geos
  - gettext
  - glib
  - gst-plugins-base
  - gstreamer
  - h5py
  - hdf4
  - hdf5
  - icu
  - idna
  - jpeg
  - kiwisolver
  - krb5
  - ld_impl_linux-64
  - libblas
  - libcblas
  - libclang
  - libcurl
  - libedit
  - libffi
  - libgcc-ng
  - libgfortran-ng
  - libgomp
  - libiconv
  - liblapack
  - libllvm9
  - libnetcdf
  - libopenblas
  - libpng
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libuuid
  - libxcb
  - libxkbcommon
  - libxml2
  - lz4-c
  - matplotlib
  - matplotlib-base
  - ncurses
  - netcdf4
  - nspr
  - nss
  - numpy
  - olefile
  - opencv
  - openssl
  - owslib
  - pandas
  - pcre
  - pillow
  - pip
  - proj
  - pthread-stubs
  - pycparser
  - pyepsg
  - pykdtree
  - pyopenssl
  - pyparsing
  - pyproj
  - pyqt
  - pyshp
  - pysocks
  - python=3.7
  - python-dateutil
  - pytz
  - qt
  - readline
  - requests
  - scipy
  - setuptools
  - shapely
  - six
  - soupsieve
  - sqlite
  - tk
  - tornado
  - trmm_rsl
  - urllib3
  - wheel
  - xarray
  - xorg-libxau
  - xorg-libxdmcp
  - xz
  - zlib
  - zstd
  - pip:
    - pyqt5-sip
    - pyqtwebengine

